kind: pipeline
type: docker
name: test

steps:
  - name: build
    image: node:latest
    commands:
      - yarn
      - yarn build:client
      - yarn build:server
    when:
      event:
        - pull_request

  - name: push docker image
    image: plugins/docker
    settings:
      registry: docker.chao.tokyo
      repo: house-temperature-web
      tags: latest
    when:
      event:
        - push
      branch:
        - master
