kind: pipeline
type: docker
name: test

steps:
  - name: build
    image: node:latest
    commands:
      - yarn
      - cp config/conf.json.sample config/conf.json
      - yarn build:client
      - yarn build:server

trigger:
  event:
    - pull_request

---
kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: ssh_host
  user:
    from_secret: ssh_user
  ssh_key:
    from_secret: ssh_key

clone:
  disable: true

steps:
  - name: pull
    commands:
      - cd /home/satoru/work/house-temperature-web
      - git pull origin master
  - name: stop old container
    commands:
      - cd /home/satoru/work/house-temperature-web
      - if [ "$(docker ps | grep 'house-temperature-web')" ]; then docker-compose down;fi
  - name: build and deploy
    depends_on:
      - pull
      - stop old container
    commands:
      - cd /home/satoru/work/house-temperature-web
      - docker-compose up --build

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - test
