version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: house-temperature-web
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379"
    command: redis-server
