version: "3"
services:
  web:
    build: .
    container_name: house-temperature-web
    depends_on:
      - redis
    ports:
      - "3000:3000"
  redis:
    image: "redis:latest"
    ports:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
