# sudo docker-compose -f docker-compose-local.yml up --build
version: "3"
services:
  web:
    build: .
    container_name: house-temperature-web
    depends_on:
      - house-temperature-web-redis
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: development
