version: "3"
services:
  web:
    build: .
    container_name: house-temperature-web
    depends_on:
      - redis
    env_file: .env
    networks:
      - common_link

networks:
  common_link:
    external: true
