version: "3"
services:
  web:
    build: .
    container_name: house-temperature-web
    depends_on:
      - redis
    networks:
      - common_link
  redis:
    image: "redis:latest"
    ports:
      - "6379"
    command: redis-server

networks:
  common_link:
    external: true
