name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: corepack yarn install --frozen-lockfile

      - name: Run lint
        run: corepack yarn lint

      - name: Build
        run: corepack yarn build

  docker-build-and-push:
    name: Build and Push to ECR
    needs: test-and-build
    if: github.event_name != 'pull_request'
    permissions:
      id-token: write
      contents: read
    uses: chao7150/actions/.github/workflows/ecr-push.yml@main
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    with:
      aws_region: ${{ vars.AWS_REGION }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
